import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, Mic, ChevronRight, Plus, Settings, Users, Loader2, X, Check } from "lucide-react";
import { useAuth } from "@/context/AuthContext";
import { useSpeechToText } from "@/hooks/useSpeechToText";
import { supabase } from "@/integrations/supabase/client";

interface LauncherPageProps {
  onEnterGroup: (groupId: string | null) => void;
  onCreateGroup?: () => void;
  onOpenSettings?: () => void;
}

// Invite codes are 8-char uppercase alphanumeric (generated by upper(substr(md5(...), 1, 8)))
const INVITE_CODE_REGEX = /^[A-Za-z0-9]{6,10}$/;

type InviteState =
  | { type: "idle" }
  | { type: "checking" }
  | { type: "found"; groupName: string; code: string }
  | { type: "already_member"; groupName: string }
  | { type: "invalid" }
  | { type: "joining" }
  | { type: "joined"; groupName: string; groupId: string };

const LauncherPage = ({ onEnterGroup, onCreateGroup, onOpenSettings }: LauncherPageProps) => {
  const { profile, groups, joinGroup, refreshGroups } = useAuth();
  const [input, setInput] = useState("");
  const [focused, setFocused] = useState(false);
  const [inviteState, setInviteState] = useState<InviteState>({ type: "idle" });

  const { listening, start: startListening, isSupported: speechSupported } = useSpeechToText({
    onResult: (transcript) => setInput((prev) => (prev ? prev + " " + transcript : transcript)),
  });

  const now = new Date();
  const greeting = now.getHours() < 12 ? "Good morning" : now.getHours() < 17 ? "Good afternoon" : "Good evening";

  const looksLikeInviteCode = (text: string): boolean => {
    const trimmed = text.trim();
    // Single word, no spaces, matches alphanumeric pattern
    return !trimmed.includes(" ") && INVITE_CODE_REGEX.test(trimmed);
  };

  const checkInviteCode = async (code: string) => {
    setInviteState({ type: "checking" });

    try {
      // Look up the group by invite code
      const { data: group } = await supabase
        .from("groups")
        .select("id, name, invite_code")
        .eq("invite_code", code.toUpperCase())
        .maybeSingle();

      if (!group) {
        setInviteState({ type: "invalid" });
        return;
      }

      // Check if already a member
      const alreadyMember = groups.some((g) => g.id === group.id);
      if (alreadyMember) {
        setInviteState({ type: "already_member", groupName: group.name });
        return;
      }

      setInviteState({ type: "found", groupName: group.name, code: code.toUpperCase() });
    } catch {
      setInviteState({ type: "invalid" });
    }
  };

  const handleJoinGroup = async () => {
    if (inviteState.type !== "found") return;
    const { code } = inviteState;
    setInviteState({ type: "joining" });

    const result = await joinGroup(code);
    if (result.error) {
      setInviteState({ type: "invalid" });
      return;
    }

    await refreshGroups();

    // Find the newly joined group
    const { data: group } = await supabase
      .from("groups")
      .select("id, name")
      .eq("invite_code", code)
      .maybeSingle();

    setInviteState({ type: "joined", groupName: result.group_name || group?.name || "Group", groupId: group?.id || "" });
    setInput("");
  };

  const dismissInvite = () => {
    setInviteState({ type: "idle" });
  };

  const handleSubmit = () => {
    if (!input.trim()) return;

    if (looksLikeInviteCode(input.trim())) {
      checkInviteCode(input.trim());
      return;
    }

    // Navigate to home with the AI input pre-filled
    onEnterGroup(null);
  };

  return (
    <div className="px-5 flex flex-col min-h-[calc(100svh-5rem)]">
      {/* Header */}
      <header className="pt-14 pb-2 flex items-start justify-between gap-3">
        <motion.h1
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-[2rem] font-bold tracking-display leading-tight"
        >
          {greeting},{" "}
          <span className="bg-gradient-to-r from-primary to-accent-foreground bg-clip-text text-transparent">
            {profile?.display_name || "there"}
          </span>
        </motion.h1>
        {onOpenSettings && (
          <button
            onClick={onOpenSettings}
            aria-label="Open settings"
            className="w-10 h-10 rounded-full border border-border bg-card text-muted-foreground hover:text-foreground hover:border-primary/30 flex items-center justify-center transition-all shadow-card"
          >
            <Settings size={17} />
          </button>
        )}
      </header>

      {/* AI Input Section */}
      <motion.div
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
        className="mt-6"
      >
        <p className="text-sm text-muted-foreground mb-3">
          What would you like to schedule today?
        </p>
        <div
          className={`relative bg-card rounded-2xl border shadow-card transition-all ${
            focused ? "border-primary shadow-lg ring-2 ring-primary/10" : "border-border"
          }`}
        >
          <textarea
            value={input}
            onChange={(e) => {
              setInput(e.target.value);
              // Reset invite state when user changes input
              if (inviteState.type !== "idle") setInviteState({ type: "idle" });
            }}
            onFocus={() => setFocused(true)}
            onBlur={() => setFocused(false)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey) {
                e.preventDefault();
                handleSubmit();
              }
            }}
            placeholder={`Try: "Dinner with Evelyn at 7pm tomorrow"\nor paste an invite code to join a group`}
            rows={3}
            className="w-full bg-transparent text-sm outline-none placeholder:text-muted-foreground resize-none p-4 pb-12"
          />
          <div className="absolute bottom-3 left-3 right-3 flex items-center justify-between">
            <div className="flex items-center gap-1.5">
              {speechSupported && (
                <button
                  onClick={startListening}
                  className={`w-8 h-8 rounded-lg flex items-center justify-center transition-colors ${
                    listening
                      ? "bg-destructive/20 text-destructive animate-pulse"
                      : "bg-secondary text-muted-foreground hover:text-foreground"
                  }`}
                >
                  <Mic size={14} />
                </button>
              )}
            </div>
            <button
              onClick={handleSubmit}
              disabled={!input.trim() || inviteState.type === "checking" || inviteState.type === "joining"}
              className="flex items-center gap-2 px-4 py-2 rounded-xl bg-gradient-to-r from-primary to-primary/80 text-primary-foreground text-sm font-semibold disabled:opacity-40 transition-all hover:shadow-md active:scale-[0.97]"
            >
              <Sparkles size={14} />
              Schedule
            </button>
          </div>
        </div>

        {/* Invite Code Detection Banner */}
        <AnimatePresence mode="wait">
          {inviteState.type === "checking" && (
            <motion.div
              key="checking"
              initial={{ opacity: 0, y: -8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              className="mt-3 flex items-center gap-3 p-4 rounded-2xl bg-secondary border border-border"
            >
              <Loader2 size={18} className="text-primary animate-spin flex-shrink-0" />
              <p className="text-sm text-muted-foreground">Checking invite code…</p>
            </motion.div>
          )}

          {inviteState.type === "found" && (
            <motion.div
              key="found"
              initial={{ opacity: 0, y: -8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              className="mt-3 p-4 rounded-2xl bg-primary/5 border border-primary/20"
            >
              <div className="flex items-start gap-3">
                <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center flex-shrink-0">
                  <Users size={18} className="text-primary" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-semibold">Join "{inviteState.groupName}"?</p>
                  <p className="text-xs text-muted-foreground mt-0.5">
                    This invite code matches a group. Would you like to join?
                  </p>
                </div>
                <button onClick={dismissInvite} className="text-muted-foreground hover:text-foreground p-1">
                  <X size={14} />
                </button>
              </div>
              <div className="flex gap-2 mt-3 ml-[52px]">
                <button
                  onClick={handleJoinGroup}
                  className="px-4 py-2 rounded-xl bg-primary text-primary-foreground text-sm font-semibold hover:opacity-90 transition-all active:scale-[0.97]"
                >
                  Join Group
                </button>
                <button
                  onClick={dismissInvite}
                  className="px-4 py-2 rounded-xl bg-secondary text-foreground text-sm font-medium hover:bg-secondary/80 transition-all"
                >
                  Cancel
                </button>
              </div>
            </motion.div>
          )}

          {inviteState.type === "joining" && (
            <motion.div
              key="joining"
              initial={{ opacity: 0, y: -8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              className="mt-3 flex items-center gap-3 p-4 rounded-2xl bg-secondary border border-border"
            >
              <Loader2 size={18} className="text-primary animate-spin flex-shrink-0" />
              <p className="text-sm text-muted-foreground">Joining group…</p>
            </motion.div>
          )}

          {inviteState.type === "joined" && (
            <motion.div
              key="joined"
              initial={{ opacity: 0, y: -8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              className="mt-3 p-4 rounded-2xl bg-primary/5 border border-primary/20"
            >
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center flex-shrink-0">
                  <Check size={18} className="text-primary" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-semibold">You've joined "{inviteState.groupName}"!</p>
                  <p className="text-xs text-muted-foreground mt-0.5">It's now in your calendars below.</p>
                </div>
              </div>
              <div className="mt-3 ml-[52px]">
                <button
                  onClick={() => {
                    if (inviteState.type === "joined" && inviteState.groupId) {
                      onEnterGroup(inviteState.groupId);
                    }
                    dismissInvite();
                  }}
                  className="px-4 py-2 rounded-xl bg-primary text-primary-foreground text-sm font-semibold hover:opacity-90 transition-all active:scale-[0.97]"
                >
                  Open Group
                </button>
              </div>
            </motion.div>
          )}

          {inviteState.type === "already_member" && (
            <motion.div
              key="already"
              initial={{ opacity: 0, y: -8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              className="mt-3 p-4 rounded-2xl bg-secondary border border-border"
            >
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-secondary flex items-center justify-center flex-shrink-0">
                  <Users size={18} className="text-muted-foreground" />
                </div>
                <div className="flex-1">
                  <p className="text-sm font-semibold">Already a member</p>
                  <p className="text-xs text-muted-foreground mt-0.5">You're already in "{inviteState.groupName}".</p>
                </div>
                <button onClick={dismissInvite} className="text-muted-foreground hover:text-foreground p-1">
                  <X size={14} />
                </button>
              </div>
            </motion.div>
          )}

          {inviteState.type === "invalid" && (
            <motion.div
              key="invalid"
              initial={{ opacity: 0, y: -8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              className="mt-3 p-4 rounded-2xl bg-destructive/5 border border-destructive/20"
            >
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-destructive/10 flex items-center justify-center flex-shrink-0">
                  <X size={18} className="text-destructive" />
                </div>
                <div className="flex-1">
                  <p className="text-sm font-semibold">Invalid invite code</p>
                  <p className="text-xs text-muted-foreground mt-0.5">That code doesn't match any group. Double-check and try again.</p>
                </div>
                <button onClick={dismissInvite} className="text-muted-foreground hover:text-foreground p-1">
                  <X size={14} />
                </button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </motion.div>


      {/* Group Calendars List */}
      <motion.div
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
        className="mt-6 flex-1"
      >
        <div className="flex items-center justify-between mb-3">
          <p className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">
            My Calendars
          </p>
          {onCreateGroup && (
            <button
              onClick={onCreateGroup}
              className="flex items-center gap-1 text-xs font-medium text-primary hover:text-primary/80 transition-colors"
            >
              <Plus size={12} />
              New
            </button>
          )}
        </div>

        <div className="space-y-2">
          {groups.map((group, index) => {
            const otherMembers = group.members.filter((m) => m.user_id !== profile?.id);
            const memberNames = otherMembers.map((m) => m.display_name || "Member").join(", ");

            return (
              <motion.button
                key={group.id}
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.25 + index * 0.05 }}
                onClick={() => onEnterGroup(group.id)}
                className="w-full flex items-center gap-4 p-4 rounded-2xl bg-card border border-border hover:border-primary/30 hover:shadow-card transition-all active:scale-[0.98] text-left group"
              >
                <div className="w-12 h-12 rounded-xl bg-secondary flex items-center justify-center text-2xl flex-shrink-0">
                  {group.emoji}
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-[15px] font-semibold truncate">{group.name}</p>
                  <p className="text-xs text-muted-foreground truncate mt-0.5">
                    {memberNames || "Just you"} · {group.members.length} member{group.members.length !== 1 ? "s" : ""}
                  </p>
                </div>
                <ChevronRight size={16} className="text-muted-foreground group-hover:text-primary transition-colors flex-shrink-0" />
              </motion.button>
            );
          })}

          {groups.length === 0 && (
            <div className="text-center py-8">
              <p className="text-sm text-muted-foreground mb-3">No calendars yet</p>
              {onCreateGroup && (
                <button
                  onClick={onCreateGroup}
                  className="px-4 py-2.5 rounded-xl bg-primary text-primary-foreground text-sm font-semibold"
                >
                  Create your first calendar
                </button>
              )}
            </div>
          )}
        </div>
      </motion.div>
    </div>
  );
};

export default LauncherPage;
