
ALTER TABLE public.events 
  ADD COLUMN IF NOT EXISTS location TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS repeat_rule JSONB DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS notification_minutes INTEGER DEFAULT -1,
  ADD COLUMN IF NOT EXISTS visibility TEXT DEFAULT 'group';

ALTER TABLE public.tasks
  ADD COLUMN IF NOT EXISTS description TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS visibility TEXT DEFAULT 'group';
